services:
  - type: web
    name: n8n-service
    runtime: image
    plan: free
    image:
      url: docker.io/n8nio/n8n:1.121.0
    envVars:
      - key: PORT
        value: "5678"

      - key: N8N_HOST
        value: ominicsr.onrender.com
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://ominicsr.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://ominicsr.onrender.com/

      - key: N8N_ENCRYPTION_KEY
        sync: false

      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_PERSONALIZATION_ENABLED
        value: "false"

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-eu-west-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "6543"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.miautytggeivqrdaewnj
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SSL
        value: "true"

      - key: EXECUTIONS_MODE
        value: regular

      - key: N8N_RUNNERS_ENABLED
        value: "true"
      - key: N8N_RUNNERS_MODE
        value: external
      - key: N8N_RUNNERS_BROKER_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: N8N_RUNNERS_AUTH_TOKEN
        sync: false
      - key: N8N_NATIVE_PYTHON_RUNNER
        value: "true"

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: N8N_SECURE_COOKIE
        value: "true"

      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: all
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: "true"
      - key: GENERIC_TIMEZONE
        value: America/New_York
      - key: TZ
        value: America/New_York
      - key: N8N_DEFAULT_BINARY_DATA_MODE
        value: filesystem

  - type: worker
    name: n8n-runners
    runtime: docker
    plan: free
    dockerfilePath: ./runners/Dockerfile
    envVars:
      - key: N8N_RUNNERS_AUTH_TOKEN
        sync: false
      - key: N8N_RUNNERS_TASK_BROKER_URI
        value: http://n8n-service:5679
      - key: N8N_RUNNERS_AUTO_SHUTDOWN_TIMEOUT
        value: "15"
